### ISSUE TITLE
module load cesium - no data

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/MAVCesium#1]
When trying to load this as a mavproxy module, it doesn't get mavlink data.

 It only works standalone.
 https://github.com/ArduPilot/MAVCesium?tab=readme-ov-file#getting-it-running-standalone
 
  The TCP socket  seems to connect and disconnect sometimes, no data arrives.

**Comment by Ryanf55** [comment]
```
Traceback (most recent call last):
  File "/home/ryan/Dev/ardu_ws/src/MAVProxy/MAVProxy/modules/mavproxy_link.py", line 1053, in master_callback
    mod.mavlink_packet(m)
  File "/home/ryan/Dev/ardu_ws/src/MAVProxy/MAVProxy/modules/mavproxy_cesium/__init__.py", line 193, in mavlink_packet
    if self.fence_change_time != self.module('fence').fenceloader.last_change:
AttributeError: 'FenceModule' object has no attribute 'fenceloader'
```

**Comment by Ryanf55** [comment]
Once I changed to use the `wploader` object, I then ran into:

Root cause: Tornado update to v5 introduce changes in event loop handling. The proposed solution worked great! 
https://github.com/tornadoweb/tornado/issues/2308#issuecomment-372661013

```
MANUAL> module load cesium
MANUAL> Using config file at /home/ryan/Dev/ardu_ws/src/MAVProxy/MAVProxy/modules/mavproxy_cesium/app/mavcesium_default.ini
Loaded module cesium
Starting Tornado server: http://0.0.0.0:5000/mavcesium/

MANUAL> websocket opened!
websocket opened!
Traceback (most recent call last):
  File "/home/ryan/Dev/ardu_ws/src/MAVProxy/MAVProxy/modules/mavproxy_link.py", line 1053, in master_callback
    mod.mavlink_packet(m)
  File "/home/ryan/Dev/ardu_ws/src/MAVProxy/MAVProxy/modules/mavproxy_cesium/__init__.py", line 181, in mavlink_packet
    self.send_data({'mav_data':msg_dict})
RuntimeError: There is no current event loop in thread 'main_loop'.
```

**Comment by Ryanf55** [comment]
Actually, AnyThreadEventLoopPolicy is now deprecated.... These libraries change faster than I can keep up.

```
/home/ryan/Dev/ardu_ws/src/MAVProxy/MAVProxy/modules/mavproxy_cesium/app/cesium_web_server.py:170: DeprecationWarning: AnyThreadEventLoopPolicy is deprecated, use asyncio.run or asyncio.new_event_loop instead
  asyncio.set_event_loop_policy(tornado.platform.asyncio.AnyThreadEventLoopPolicy())
  ```
  
  The docs say to use asyncio's base functions in tornado 6.
  https://www.tornadoweb.org/en/stable/asyncio.html#module-tornado.platform.asyncio
  
  Cesium is using tornado 6.4.1. I don't have much understanding of how these two interract.
